image: Ubuntu

environment:
  matrix:
    - CC: clang
      CXX: clang++
    - CC: gcc
      CXX: g++

configuration:
  - Debug
  - Release

for:
  -
    matrix:
      only:
        - configuration: Debug
          CC: clang
    environment:
      CFLAGS: -Og -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic
      CXXFLAGS: -Og -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic

  -
    matrix:
      only:
        - configuration: Release
          CC: clang
    environment:
      CFLAGS: -O2
      CXXFLAGS: -O2

  -
    matrix:
      only:
        - configuration: Debug
          CC: gcc
    environment:
      CFLAGS: -Og -g -Wall -Wextra
      CXXFLAGS: -Og -g -Wall -Wextra

  -
    matrix:
      only:
        - configuration: Release
          CC: gcc
    environment:
      CFLAGS: -O2
      CXXFLAGS: -O2

init:
  - $CC --version
  - $CXX --version
  - cmake --version

before_build:
  - cd $APPVEYOR_BUILD_FOLDER
  - mkdir build
  - cd build

build_script:
  - cmake .. -DCMAKE_BUILD_TYPE=$configuration -DCMAKE_INSTALL_PREFIX=/var/tmp/unshield
  - cmake --build .
  - cmake --install .

test_script:
  - ../run-tests.sh
