dist: trusty
sudo: false

language: c

os: linux

compiler:
  - gcc
  - clang

env:
  matrix:
    - USE_OUR_OWN_MD5=0 CFLAGS="-O2" LDFLAGS="-s"
    - USE_OUR_OWN_MD5=1 CFLAGS="-O2" LDFLAGS="-s"
    - USE_OUR_OWN_MD5=0 CFLAGS="-Og -g -Wall -Wextra"
    - USE_OUR_OWN_MD5=1 CFLAGS="-Og -g -Wall -Wextra"

script:
  - mkdir build
  - cd build
  - cmake -DUSE_OUR_OWN_MD5=${USE_OUR_OWN_MD5} ..
  - cmake --build .
  - make install
  - ../run-tests.sh

